version: '3'

services:
  git:
    image: alpine:git-server
    container_name: git
    ports:
      - "2222:22"
    volumes:
      - "/home/<USER>/git-server/repos/:/git-server/repos"
      - "/home/<USER>/git-server/keys/:/git-server/keys"
    build:
        context: .
        dockerfile: Dockerfile

